### ISSUE TITLE
Crash on release build 200125

### ISSUE THREAD

**Issue by otormaigh** [otormaigh/lekkie-android#31]
related google issue https://issuetracker.google.com/issues/120277396

```
2018-12-01 14:31:44.735 E/AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
    Process: ie.pennylabs.lekkie, PID: 5368
    java.lang.ExceptionInInitializerError
        at com.google.android.gms.phenotype.Phenotype.getContentProviderUri(Unknown Source:0)
        at com.google.android.gms.internal.clearcut.zzp.<clinit>(Unknown Source:10)
        at com.google.firebase.perf.internal.zzd.zzbd(Unknown Source:32)
        at com.google.firebase.perf.internal.zzd.zzb(Unknown Source:83)
        at com.google.firebase.perf.internal.zze.run(Unknown Source:1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NullPointerException: throw with null exception
        at com.google.android.gms.phenotype.Phenotype.<clinit>(Unknown Source:3)
        at com.google.android.gms.phenotype.Phenotype.getContentProviderUri(Unknown Source:0) 
        at com.google.android.gms.internal.clearcut.zzp.<clinit>(Unknown Source:10) 
        at com.google.firebase.perf.internal.zzd.zzbd(Unknown Source:32) 
        at com.google.firebase.perf.internal.zzd.zzb(Unknown Source:83) 
        at com.google.firebase.perf.internal.zze.run(Unknown Source:1) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
2018-12-01 14:31:44.822 D/OpenGLRenderer: HWUI GL Pipeline
2018-12-01 14:31:44.856 I/FirebasePerformance: Session ID - xxxxxxxxxxxx
2018-12-01 14:31:44.858 D/FirebasePerformance: onResume(): ie.pennylabs.lekkie.feature.main.MainActivity: 319318 microseconds
2018-12-01 14:31:44.861 E/AndroidRuntime: FATAL EXCEPTION: pool-4-thread-2
    Process: ie.pennylabs.lekkie, PID: 5368
    java.lang.NullPointerException: Attempt to read from field 'com.google.firebase.perf.internal.zzx com.google.firebase.perf.internal.zzv.zzeo' on a null object reference
        at com.google.firebase.perf.internal.zzi.run(Unknown Source:3)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2018-12-01 14:31:44.863 D/AndroidRuntime: Shutting down VM
2018-12-01 14:31:44.863 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ie.pennylabs.lekkie, PID: 5368
    java.lang.ExceptionInInitializerError
        at com.google.android.gms.internal.firebase-perf.zzhn.<clinit>(Unknown Source:7)
        at com.google.android.gms.internal.firebase-perf.zzhi.<clinit>(Unknown Source:1)
        at com.google.android.gms.internal.firebase-perf.zzcs$zzb.<clinit>(Unknown Source:1)
        at com.google.android.gms.internal.firebase-perf.zzcs.zza(Unknown Source:36)
        at com.google.android.gms.internal.firebase-perf.zzed.zzb(Unknown Source:6)
        at com.google.android.gms.internal.firebase-perf.zzfe.zzb(Unknown Source:3)
        at com.google.android.gms.internal.firebase-perf.zzfc.zzd(Unknown Source:2)
        at com.google.android.gms.internal.firebase-perf.zzfz.zze(Unknown Source:3)
        at com.google.android.gms.internal.firebase-perf.zzfz.zzn(Unknown Source:1)
        at com.google.android.gms.internal.firebase-perf.zzee$zza.zzhw(Unknown Source:5)
        at com.google.android.gms.internal.firebase-perf.zzee$zza.zzhx(Unknown Source:1)
        at com.google.firebase.perf.metrics.AppStartTrace.onActivityResumed(Unknown Source:22)
        at android.app.Application.dispatchActivityResumed(Application.java:216)
        at android.app.Activity.onResume(Activity.java:1313)
        at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:1)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
        at android.app.Activity.performResume(Activity.java:7117)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: throw with null exception
        at com.google.android.gms.internal.firebase-perf.zzdj.<clinit>(Unknown Source:3)
        at com.google.android.gms.internal.firebase-perf.zzhn.<clinit>(Unknown Source:7) 
        at com.google.android.gms.internal.firebase-perf.zzhi.<clinit>(Unknown Source:1) 
        at com.google.android.gms.internal.firebase-perf.zzcs$zzb.<clinit>(Unknown Source:1) 
        at com.google.android.gms.internal.firebase-perf.zzcs.zza(Unknown Source:36) 
        at com.google.android.gms.internal.firebase-perf.zzed.zzb(Unknown Source:6) 
        at com.google.android.gms.internal.firebase-perf.zzfe.zzb(Unknown Source:3) 
        at com.google.android.gms.internal.firebase-perf.zzfc.zzd(Unknown Source:2) 
        at com.google.android.gms.internal.firebase-perf.zzfz.zze(Unknown Source:3) 
        at com.google.android.gms.internal.firebase-perf.zzfz.zzn(Unknown Source:1) 
        at com.google.android.gms.internal.firebase-perf.zzee$zza.zzhw(Unknown Source:5) 
        at com.google.android.gms.internal.firebase-perf.zzee$zza.zzhx(Unknown Source:1) 
        at com.google.firebase.perf.metrics.AppStartTrace.onActivityResumed(Unknown Source:22) 
        at android.app.Application.dispatchActivityResumed(Application.java:216) 
        at android.app.Activity.onResume(Activity.java:1313) 
        at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:1) 
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355) 
        at android.app.Activity.performResume(Activity.java:7117) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

**Comment by otormaigh** [comment]
Looks like a fix was added. No issues when deploying locally. May aswell us that until a new version of r8 has been released.

https://issuetracker.google.com/issues/120277396#comment7
